### ISSUE TITLE
Scoring

### ISSUE THREAD

**Issue by vab9** [vab9/serious-game#10]
Ideal wäre es, wenn man Punkte nicht nur hinzufügen / abziehen kann, wenn der Spieler die Seite wechselt.

Hierfür wäre es gut, wenn wir einen simplen Weg finden, wie man Variablen zwischen der Twine Engine und unserem Javascript hin und her bewegen kann. Hatte dazu ein paar Sachen gelesen, aber die Sahen eher umständlich aus...

Damit der Spieler sich mit anderen vergleichen kann, müssen wir die Highscores auf unserem Server speichern. Wir sollten uns also bald überlegen, wie wir das Spiel hosten wollen.

**Comment by vab9** [comment]
Man könnte einfach mit einem hook den link auf die eigene passage verweisen und dadurch sozusagen einen Refresh simulieren. Das wuerde dann den score auch updaten...

**Comment by DaveDavidson** [comment]
Habe das mit der "Link:... []..."-Syntax gemacht, die du als Beispiel vorgegeben hattest. Habe alle Entscheidungssituationen mit Score-Auswirkungen verknüpft.
