### ISSUE TITLE
Issues chapter 2

### ISSUE THREAD

**Issue by DaveDavidson** [vab9/serious-game#13]
- [x] F1.3.1: Namen-Variable des Spielers einfügen

- [x] Erklärung zu den Verlinkungen (blau-unterlegte Hyperlinks) in der Einführung/Hilfe geben

- [x] F1.11 und F2.8 und F3.11: Punktestand für das Kapitel

- [x] Bilder-Skalierung anpassen

- [x] F2.4: Zurück-Button, um weitere Passwörter auszuprobieren, nachdem man die Tipps gelesen hat

**Comment by vab9** [comment]
Zu der Bilder Skalierung: Für die Susi Bilder ist es am einfachsten, wenn wir eine CSS Klasse erstellen und diese an jedes dieser Avatar-Bilder ranhängen. Dann können wir sie alle auf einmal skalieren. Diese sollen ja wahrscheinlich auch alles gleich groß sein...
