### ISSUE TITLE
Kapitel aufeinander abstimmen

### ISSUE THREAD

**Issue by vab9** [vab9/serious-game#15]
Zur Zeit ist es noch viel zu Offensichtlich, dass verschiedene Leute die Kapitel geschrieben haben. Bei Sascha spricht Susi den Spieler direkt an und bei Kai ist Susi eine dritte Person...

**Comment by DaveDavidson** [comment]
Das mache ich am WE.

**Comment by DaveDavidson** [comment]
Sind mehr oder weniger aufeinander abgestimmt.
