### ISSUE TITLE
Was noch fehlt - Small Fixes

### ISSUE THREAD

**Issue by DaveDavidson** [vab9/serious-game#31]
- [x] Videos werden nicht angezeigt: Firefox

- [x] Videos aus Kapitel 1 bleiben ohne Bild, Ton funktioniert. Videos aus Kapitel 2+3 funktionieren auch: Chrome

- [ ] Drag and Drop: Fehlermeldung nach einiger Zeit, danach kann weitergemacht werden: Chrome

- [ ] Drag and Drop: Die letzte Meldung "Super! Alle Maßnahmen wurden richtig zugeordnet!" kommt immer wieder, wenn nach dem letzten "Drop" eines der grauen Felder bewegt.

- [x] Susi1234-Folie

- [x] Startseite anpassen: Duzen

**Comment by vab9** [comment]
Bei Drag and Drop sich wiederholende Meldung: Das liegt am Javascript, da wird eine appendchild methode aufgerufen. Es sollte wohl besser replaced werden, damit es sich nicht aufaddiert

**Comment by vab9** [comment]
Kann die Fehlermeldung in Chrome nicht reproduzieren
