### ISSUE TITLE
Startseite

### ISSUE THREAD

**Issue by DaveDavidson** [vab9/serious-game#32]
Aus dem Feedback von der MS4-Präsi:

- [x] Lernstand: Wo habe ich das letzte Mal aufgehört?

- [ ] Informationen über den Punktestand: Punkte letzte Session / Average Punkte aller Spieler mit meinen verglichen

**Comment by DaveDavidson** [comment]
Startseite erstellt, Funktionalität fehlt aber noch.

**Comment by vab9** [comment]
Average Punkte wontfix
