### ISSUE TITLE
Score-System

### ISSUE THREAD

**Issue by DaveDavidson** [vab9/serious-game#34]
Feedback aus der MS4-Präsi:

- [x] Ranking-System wie im studip mit verschiedenen Rängen (Anfänger / Fortgeschrittener / Experte / ... )

- [x] Top10-Seite erstellt

- [x] Top10-Seite mit Funktionalität versehen

**Comment by vab9** [comment]
weiteres beispiel mit php
http://wiki.unity3d.com/index.php?title=Server_Side_Highscores

**Comment by vab9** [comment]
Top10 Funktionalität ist da
