### ISSUE TITLE
Website Tests

### ISSUE THREAD

**Issue by DaveDavidson** [vab9/serious-game#37]
Tools und Websites um unsere Website zu testen:

- https://www.totalvalidator.com/

- https://www.w3.org/WAI/eval/Overview.html

- http://colorfilter.wickline.org/?a=1;r=;l=0;j=1;u=www.dorfgemeinschaft20.de;t=p

--> Funktioniert nicht, da wir keine normale HTML-Seite haben

**Comment by vab9** [comment]
Jo die Resourcen auf diesen Webseiten sind fuer uns nicht von Nutzen
