### ISSUE TITLE
Nameneingabe

### ISSUE THREAD

**Issue by DaveDavidson** [vab9/serious-game#40]
Netteres Fenster bei der Nameneingabe.

Außerdem fehlt, dass der Spieler "Spieler" genannt wird, wenn kein Name eingegeben wurde.

**Comment by vab9** [comment]
Spieler wird jetzt Spieler genannt, wenn das Eingabefeld leer gelassen wird...
Das Fenster ist browserspezifisch und kann von uns nicht gestylt werden.
