### ISSUE TITLE
Save States

### ISSUE THREAD

**Issue by vab9** [vab9/serious-game#48]
detect when game is closed with window.onbeforeunload()...

**Comment by vab9** [comment]
- maybe use python shelve or pickle to serialize game scores

**Comment by vab9** [comment]
http://stackoverflow.com/questions/23949906/highscores-using-python-saving-10-highscores-and-ordering-them

**Comment by vab9** [comment]
example using asp and c++

**Comment by vab9** [comment]
example with php and mysql http://gamedevelopment.tutsplus.com/tutorials/how-to-code-a-self-hosted-phpsql-leaderboard-for-your-game--gamedev-11627

**Comment by DaveDavidson** [comment]
Automatically Saving the Game in Harlowe:

https://twinery.org/forum/discussion/5643/automatically-saving-the-game-in-harlowe#latest

**Comment by DaveDavidson** [comment]
SaveGame ist jetzt erstmal lokal (per Cookie) gespeichert und wird automatisch geladen, wenn man sich einloggt.

**Comment by DaveDavidson** [comment]
Spielstand darf nicht gespeichert werden, wenn man anonym (als "Spieler") spielt.
