### ISSUE TITLE
Fehlermeldung bei Anmeldung

### ISSUE THREAD

**Issue by 953359** [vab9/serious-game#80]
![unbenannt](https://cloud.githubusercontent.com/assets/22678559/19186829/6d915ae0-8c88-11e6-8380-eaa260b4a310.png)
Browser: Internetexplorer 11

**Comment by vab9** [comment]
Hallo @953359 ,

Danke für die Fehlermeldung! Da unser Spiel relativ moderne JavaScript Funktionen benutzt, werden leider nur die Browser Chrome (Versionen ~40+) und Firefox (Versionen ~42+)  offiziell unterstützt. Kannst du vielleicht einmal testen, ob auch mit einem richtigen Browser diese Fehlermeldung kommt? 

Wir arbeiten schon daran, dem Nutzer einen Hinweis anzuzeigen, wenn der falsche Browser verwendet wird. ( siehe issue  #77 )

Danke für deine Hilfe!

**Comment by vab9** [comment]
Ich schliesse diesen issue mal, da es ja wohl am IE lag...
